# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  testjob:
    docker: 
      - image: circleci/php
    steps:
      - checkout
      - run: sudo apt-get update && apt-get -y install rsync git subversion wget zip unzip
      - run: rsync -avz $CIRCLE_WORKING_DIRECTORY leon@cloud.einfach123.de:/home/leon/ci/
workflows:
  # Name the workflow "welcome"
  deploy:
    # Run the welcome/run job in its own container
    jobs:
      - testjob:
          filters:
            branches:
              only: master